apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: database-broker
  namespace: test-ns
spec:
  clusterServiceClassExternalName: database-broker
  clusterServicePlanExternalName: default
  parameters:
    param-1: value-1
    param-2: value-2
